export LAB_LOCATION="italynorth"
export LAB_SUFFIX="2088dddf"
export LAB_RG="rg-cea-ud02-${LAB_SUFFIX}"
export LAB_VNET="vnet-cea-ud02"
export LAB_SUBNET="snet-app"
export LAB_STORAGE="stcea${LAB_SUFFIX}"
export LAB_DELETE_AFTER="$(date -v+2d +%F)"